"""Post-pilot verification only; does not import the compiler or evaluator.

Run from the repository root. Writes JSON to stdout so historical results need
not be replaced. The expected quantitative mapping is checked directly against
raw model selections, not generated by the production compilation function.
"""
import json
from pathlib import Path


def read(path):
    return json.loads(path.read_text())


records = []
for accepted in sorted(Path('artifacts/stage4/pilot/semantic').glob('*/accepted')):
    sequence = read(accepted.parent / 'sequence.json')
    final = next(s for s in reversed(sequence) if s.get('stopping_decision') == 'valid final specification')
    raw = json.loads(final['raw_output'])
    intents = raw['answers']
    selected_ids = {a['evidence_id'] for a in intents}
    selected_quantitative = {
        ('comparison' if a['kind'] == 'peer_comparison' else 'personal_change', a['evidence_id'])
        for a in intents if a['kind'] in {'peer_comparison', 'personal_change'}
    }
    spec = read(accepted / 'spec.json')
    evidence = read(accepted / 'evidence.json')
    bound = read(accepted / 'bound.json')
    provenance = read(accepted / 'selection_provenance.json')
    retrieved = read(accepted.parent / 'tool_results.json')
    assert set(evidence) == selected_ids == set(spec['evidence_ids']) == set(bound['evidence_hashes'])
    assert selected_ids <= set(retrieved)
    actual_quantitative = {
        (c['template'], c['evidence_id']) for c in spec['claims']
        if c['template'] in {'comparison', 'personal_change'}
    }
    assert actual_quantitative == selected_quantitative
    assert len(provenance['claims']) == len(spec['claims'])
    assert len(provenance['panels']) == len(spec['panels'])
    for claim, origin in zip(spec['claims'], provenance['claims']):
        if claim['template'] in {'comparison', 'personal_change'}:
            assert origin['origin'] == 'method_selected' and origin['answer_indices']
            expected_kind = 'peer_comparison' if claim['template'] == 'comparison' else 'personal_change'
            assert all(intents[i]['kind'] == expected_kind and intents[i]['evidence_id'] == claim['evidence_id']
                       for i in origin['answer_indices'])
    comparison_panels = {(p['kind'], p['evidence_id']) for p in spec['panels'] if p['kind'] == 'comparison'}
    assert comparison_panels == {c for c in selected_quantitative if c[0] == 'comparison'}
    for claim in bound['claims']:
        if claim['template'] in {'comparison', 'personal_change'}:
            assert (claim['template'], claim['evidence_id']) in selected_quantitative
            assert claim['selection_origin'] == 'method_selected'
    records.append({
        'question_id': spec['question_id'], 'status': 'PASS',
        'raw_generation': final['generation_metadata']['generation'],
        'explicit_intents': len(intents), 'selected_evidence': sorted(selected_ids),
        'retrieved_unselected_evidence': sorted(set(retrieved) - selected_ids),
        'quantitative_claims': len(actual_quantitative),
        'compiler_panels': [dict(panel, **origin) for panel, origin in zip(spec['panels'], provenance['panels'])
                            if origin['origin'] == 'compiler_supplied'],
        'compiler_quantitative_claims': 0,
    })
assert len(records) == 7
print(json.dumps({'status': 'PASS', 'phase': 'post-pilot verification, not scoring or tuning',
                  'production_compiler_or_evaluator_called': False,
                  'accepted_semantic_pilot_dashboards': len(records), 'records': records}, indent=2))
